name: cosmos
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - libffi=3.4.2
  - openssl=1.1.1q
  - pip=22.2.2
  - python=3.10.6
  - setuptools=63.4.1
  - sqlite=3.39.3
  - tk=8.6.12
  - tzdata=2022e
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.6
  - zlib=1.2.12
  - pip:
    - affine==2.3.1
    - alabaster==0.7.12
    - appdirs==1.4.4
    - arrow==1.2.3
    - astroid==2.12.11
    - atomicwrites==1.4.1
    - attrs==22.1.0
    - autopep8==1.6.0
    - babel==2.10.3
    - backcall==0.2.0
    - bcrypt==4.0.1
    - beautifulsoup4==4.11.1
    - binaryornot==0.4.4
    - black==22.10.0
    - bleach==5.0.1
    - cached-property==1.5.2
    - cffi==1.15.1
    - cftime==1.6.2
    - chardet==5.0.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - click-plugins==1.1.1
    - cligj==0.7.2
    - cloudpickle==2.2.0
    - colorama==0.4.5
    - contourpy==1.0.5
    - cookiecutter==2.1.1
    - cryptography==38.0.1
    - cycler==0.11.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - diff-match-patch==20200713
    - dill==0.3.5.1
    - docutils==0.19
    - elementpath==3.0.2
    - entrypoints==0.4
    - fastjsonschema==2.16.2
    - flake8==4.0.1
    - fonttools==4.37.4
    - geojson==2.5.0
    - h5py==3.7.0
    - idna==3.4
    - imagesize==1.4.1
    - inflection==0.5.1
    - intervaltree==3.1.0
    - ipykernel==6.16.0
    - ipython==7.34.0
    - ipython-genutils==0.2.0
    - isodate==0.6.1
    - isort==5.10.1
    - jaraco-classes==3.2.3
    - jedi==0.18.1
    - jellyfish==0.9.0
    - jinja2==3.1.2
    - jinja2-time==0.2.0
    - jsonschema==4.16.0
    - jupyter-client==7.4.2
    - jupyter-core==4.11.1
    - jupyterlab-pygments==0.2.2
    - keyring==23.9.3
    - kiwisolver==1.4.4
    - lazy-object-proxy==1.7.1
    - lxml==4.9.1
    - markupsafe==2.1.1
    - mat73==0.59
    - matplotlib==3.6.1
    - matplotlib-inline==0.1.6
    - mccabe==0.6.1
    - metpy==1.3.1
    - mistune==2.0.4
    - more-itertools==9.0.0
    - mypy-extensions==0.4.3
    - nbclient==0.7.0
    - nbconvert==7.2.1
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - netcdf4==1.6.2
    - noaa-coops==0.1.9
    - numpy==1.23.4
    - numpydoc==1.5.0
    - packaging==21.3
    - pandas==1.5.0
    - pandocfilters==1.5.0
    - paramiko==2.11.0
    - parso==0.8.3
    - pathspec==0.10.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - pint==0.19.2
    - platformdirs==2.5.2
    - pluggy==1.0.0
    - pooch==1.6.0
    - prompt-toolkit==3.0.31
    - protobuf==4.21.8
    - psutil==5.9.2
    - ptyprocess==0.7.0
    - pycodestyle==2.8.0
    - pycparser==2.21
    - pydocstyle==6.1.1
    - pyflakes==2.4.0
    - pygments==2.13.0
    - pylint==2.15.4
    - pyls-spyder==0.4.0
    - pynacl==1.5.0
    - pyparsing==3.0.9
    - pyproj==3.4.0
    - pyqt5==5.15.7
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - pyqtwebengine==5.15.6
    - pyqtwebengine-qt5==5.15.2
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - python-lsp-black==1.2.1
    - python-lsp-jsonrpc==1.0.0
    - python-lsp-server==1.5.0
    - python-slugify==6.1.2
    - pytoolconfig==1.2.2
    - pytz==2022.5
    - pywin32==304
    - pywin32-ctypes==0.2.0
    - pyyaml==6.0
    - pyzmq==24.0.1
    - qdarkstyle==3.0.3
    - qstylizer==0.2.2
    - qtawesome==1.1.1
    - qtconsole==5.3.2
    - qtpy==2.2.1
    - rasterio==1.3.2
    - requests==2.28.1
    - requests-file==1.5.1
    - requests-toolbelt==0.10.0
    - rope==1.3.0
    - rtree==1.0.1
    - scipy==1.9.2
    - siphon==0.9
    - six==1.16.0
    - snowballstemmer==2.2.0
    - snuggs==1.4.7
    - sortedcontainers==2.4.0
    - soupsieve==2.3.2.post1
    - sphinx==5.3.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - spyder==5.3.3
    - spyder-kernels==2.3.3
    - text-unidecode==1.3
    - textdistance==4.5.0
    - three-merge==0.1.1
    - tinycss2==1.2.1
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.11.5
    - tornado==6.2
    - traitlets==5.5.0
    - ujson==5.5.0
    - urllib3==1.26.12
    - watchdog==2.1.9
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - wget==3.2
    - whatthepatch==1.0.2
    - wrapt==1.14.1
    - xarray==2022.10.0
    - yapf==0.32.0
    - zeep==4.1.0
