name: cosmos
 
channels:
  - conda-forge
  - numba
 
dependencies:
  - black
  - build
  - datashader
  - geopandas
  - mypy
  - numpy
  - pandas
  - plotly
  - pydantic
  - pytest
  - python=3.10
  - tomli
  - tomli-w
  - twine
  - pip
  - pip:
    - noaa-coops
    - NDBC
    - paramiko
    - boto3
    - hera
    - wget
    - awscli
