name: cosmos
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - appdirs=1.4.4
  - argh=0.26.2
  - arrow=1.2.2
  - astroid=2.9.0
  - atomicwrites=1.4.0
  - autopep8=1.6.0
  - babel=2.8.0
  - backcall=0.2.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.10.0
  - binaryornot=0.4.4
  - black=19.3b0
  - bleach=3.2.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - cartopy=0.20.2
  - certifi=2021.10.8
  - cffi=1.15.0
  - cftime=1.6.0
  - chardet=4.0.0
  - charset-normalizer=2.0.12
  - click=7.1.2
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cookiecutter=1.7.3
  - cryptography=36.0.1
  - curl=7.82.0
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20200713
  - docutils=0.18.1
  - entrypoints=0.4
  - flake8=4.0.1
  - freetype=2.10.4
  - geojson=2.5.0
  - geos=3.10.2
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=58.2
  - idna=3.3
  - imagesize=1.2.0
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.4.0
  - inflection=0.5.1
  - intel-openmp=2022.0.0
  - intervaltree=3.1.0
  - ipykernel=6.9.2
  - ipython=7.32.0
  - ipython_genutils=0.2.0
  - isort=5.6.4
  - jbig=2.1
  - jedi=0.18.1
  - jellyfish=0.9.0
  - jinja2=2.11.2
  - jinja2-time=0.2.0
  - jpeg=9e
  - jsonschema=3.2.0
  - jupyter_client=7.1.2
  - jupyter_core=4.9.2
  - keyring=23.4.0
  - kiwisolver=1.4.0
  - krb5=1.19.3
  - lazy-object-proxy=1.7.1
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.82.0
  - libdeflate=1.10
  - libffi=3.4.2
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libpng=1.6.37
  - libprotobuf=3.19.4
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzip=1.8.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.0.1
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - mccabe=0.6.1
  - metpy=1.2.0
  - mistune=0.8.4
  - mkl=2022.0.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nbconvert=5.5.0
  - nbformat=5.0.8
  - nest-asyncio=1.5.4
  - netcdf4=1.5.8
  - numpy=1.22.3
  - numpydoc=1.1.0
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.4.1
  - pandoc=2.11
  - pandocfilters=1.5.0
  - paramiko=2.7.2
  - parso=0.8.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pint=0.18
  - pip=22.0.4
  - platformdirs=2.5.1
  - pluggy=0.12.0
  - pooch=1.6.0
  - poyo=0.5.0
  - proj=9.0.0
  - prompt-toolkit=3.0.8
  - protobuf=3.19.4
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pydocstyle=5.1.1
  - pyflakes=2.4.0
  - pygments=2.7.1
  - pylint=2.12.2
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyproj=3.3.0
  - pyqt=5.9.2
  - pyrsistent=0.18.1
  - pyshp=2.2.0
  - pysocks=1.7.1
  - python=3.9.10
  - python-dateutil=2.8.2
  - python-lsp-black=1.1.0
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.3.3
  - python-slugify=4.0.1
  - python_abi=3.9
  - pytz=2021.3
  - pywin32=303
  - pywin32-ctypes=0.2.0
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qdarkstyle=3.0.2
  - qstylizer=0.2.1
  - qt=5.9.7
  - qtawesome=1.1.1
  - qtconsole=5.2.2
  - qtconsole-base=5.2.2
  - qtpy=1.9.0
  - requests=2.27.1
  - rope=0.18.0
  - rtree=0.9.7
  - scipy=1.8.0
  - setuptools=60.10.0
  - shapely=1.8.0
  - sip=4.19.13
  - siphon=0.9
  - six=1.16.0
  - snowballstemmer=2.0.0
  - sortedcontainers=2.2.2
  - soupsieve=2.3.1
  - sphinx=3.2.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - spyder=5.2.2
  - spyder-kernels=2.2.1
  - sqlite=3.37.1
  - tbb=2021.5.0
  - testpath=0.4.4
  - text-unidecode=1.3
  - textdistance=4.2.2
  - three-merge=0.1.1
  - tinycss2=1.1.1
  - tk=8.6.12
  - toml=0.10.1
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - ucrt=10.0.20348.0
  - ujson=5.1.0
  - unidecode=1.1.1
  - urllib3=1.26.9
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wrapt=1.11.2
  - xarray=2022.3.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - attrs==21.4.0
    - cached-property==1.5.2
    - isodate==0.6.1
    - lxml==4.8.0
    - noaa-coops==0.1.9
    - pycryptodome==3.14.1
    - requests-file==1.5.1
    - requests-toolbelt==0.9.1
    - zeep==4.1.0
