[[station]]
name = "41001"
ndbc_id = "41001"
longname = "EAST HATTERAS - 150 NM East of Cape Hatteras"
longitude = -72.196
latitude = 34.751
type = "wave_buoy"

[[station]]
name = "41002"
ndbc_id = "41002"
longname = "SOUTH HATTERAS - 225 NM South of Cape Hatteras"
longitude = -74.945
latitude = 31.76
type = "wave_buoy"

[[station]]
name = "41004"
ndbc_id = "41004"
longname = "EDISTO - 41 NM Southeast of Charleston, SC"
longitude = -79.099
latitude = 32.502
type = "wave_buoy"

[[station]]
name = "41008"
ndbc_id = "41008"
longname = "GRAYS REEF - 40 NM Southeast of Savannah, GA"
longitude = -80.866
latitude = 31.4
type = "wave_buoy"

[[station]]
name = "41009"
ndbc_id = "41009"
longname = "CANAVERAL 20 NM East of Cape Canaveral, FL"
longitude = -80.185
latitude = 28.508
type = "wave_buoy"

[[station]]
name = "41010"
ndbc_id = "41010"
longname = "CANAVERAL EAST - 120NM East of Cape Canaveral"
longitude = -78.485
latitude = 28.878
type = "wave_buoy"

[[station]]
name = "41013"
ndbc_id = "41013"
longname = "Frying Pan Shoals, NC"
longitude = -77.764
latitude = 33.441
type = "wave_buoy"

[[station]]
name = "41025"
ndbc_id = "41025"
longname = "Diamond Shoals, NC"
longitude = -75.454
latitude = 35.01
type = "wave_buoy"

[[station]]
name = "41040"
ndbc_id = "41040"
longname = "NORTH EQUATORIAL ONE- 470 NM East of Martinique"
longitude = -53.341
latitude = 14.542
type = "wave_buoy"

[[station]]
name = "41041"
ndbc_id = "41041"
longname = "NORTH EQUATORIAL TWO - 890 NM East of Martinique "
longitude = -56.3313
latitude = 15.5097
type = "wave_buoy"

[[station]]
name = "41043"
ndbc_id = "41043"
longname = "NE PUERTO RICO - 170 NM NNE of San Juan, PR"
longitude = -64.79
latitude = 21.03
type = "wave_buoy"

[[station]]
name = "41044"
ndbc_id = "41044"
longname = "NE ST MARTIN - 330 NM NE St Martin Is"
longitude = -58.63
latitude = 21.582
type = "wave_buoy"

[[station]]
name = "41046"
ndbc_id = "41046"
longname = "EAST BAHAMAS - 335 NM East of San Salvador Is,  Bahamas "
longitude = -68.384
latitude = 23.822
type = "wave_buoy"

[[station]]
name = "41047"
ndbc_id = "41047"
longname = "NE BAHAMAS - 350 NM ENE of Nassau, Bahamas"
longitude = -71.466
latitude = 27.463
type = "wave_buoy"

[[station]]
name = "41048"
ndbc_id = "41048"
longname = "WEST BERMUDA - 240 NM West of Bermuda"
longitude = -69.573
latitude = 31.831
type = "wave_buoy"

[[station]]
name = "41049"
ndbc_id = "41049"
longname = "SOUTH BERMUDA - 300 NM SSE of Bermuda"
longitude = -62.938
latitude = 27.49
type = "wave_buoy"

[[station]]
name = "41x01"
ndbc_id = "41x01"
longname = "Adrift from 41001, 150nm E of Cape Hatteras"
longitude = -43.5672
latitude = 34.3553
type = "wave_buoy"

[[station]]
name = "42001"
ndbc_id = "42001"
longname = "MID GULF - 180 nm South of Southwest Pass, LA"
longitude = -89.657
latitude = 25.942
type = "wave_buoy"

[[station]]
name = "42002"
ndbc_id = "42002"
longname = "WEST GULF - 207 NM East of Brownsville, TX"
longitude = -93.646
latitude = 26.055
type = "wave_buoy"

[[station]]
name = "42003"
ndbc_id = "42003"
longname = "East GULF - 208 NM West of Naples, FL"
longitude = -85.615
latitude = 25.925
type = "wave_buoy"

[[station]]
name = "42012"
ndbc_id = "42012"
longname = "ORANGE BEACH - 44 NM SE of Mobile, AL"
longitude = -87.548
latitude = 30.06
type = "wave_buoy"

[[station]]
name = "42019"
ndbc_id = "42019"
longname = "FREEPORT, TX - 60 NM South of Freeport, TX"
longitude = -95.345
latitude = 27.91
type = "wave_buoy"

[[station]]
name = "42020"
ndbc_id = "42020"
longname = "CORPUS CHRISTI, TX - 60NM SSE of Corpus Christi, TX"
longitude = -96.693
latitude = 26.968
type = "wave_buoy"

[[station]]
name = "42035"
ndbc_id = "42035"
longname = "GALVESTON,TX -  22 NM East of Galveston, TX"
longitude = -94.413
latitude = 29.232
type = "wave_buoy"

[[station]]
name = "42036"
ndbc_id = "42036"
longname = "WEST TAMPA  - 112 NM WNW of Tampa, FL"
longitude = -84.508
latitude = 28.501
type = "wave_buoy"

[[station]]
name = "42039"
ndbc_id = "42039"
longname = "PENSACOLA - 115NM SSE of Pensacola, FL"
longitude = -86.007
latitude = 28.787
type = "wave_buoy"

[[station]]
name = "42040"
ndbc_id = "42040"
longname = "LUKE OFFSHORE TEST PLATFORM - 63 NM South of Dauphin Island, AL"
longitude = -88.237
latitude = 29.207
type = "wave_buoy"

[[station]]
name = "42055"
ndbc_id = "42055"
longname = "BAY OF CAMPECHE - 214 NM NE of Veracruz, MX"
longitude = -93.941
latitude = 22.124
type = "wave_buoy"

[[station]]
name = "42056"
ndbc_id = "42056"
longname = " Yucatan Basin - 120 NM ESE of Cozumel, MX"
longitude = -84.945
latitude = 19.82
type = "wave_buoy"

[[station]]
name = "42057"
ndbc_id = "42057"
longname = "Western Caribbean - 195 NM WSW of Negril, Jamaica"
longitude = -81.422
latitude = 16.908
type = "wave_buoy"

[[station]]
name = "42058"
ndbc_id = "42058"
longname = "Central Caribbean - 210 NM SSE of Kingston, Jamaica"
longitude = -74.816
latitude = 14.394
type = "wave_buoy"

[[station]]
name = "42059"
ndbc_id = "42059"
longname = "Eastern Caribbean Sea - 180 NM SSW of Ponce, PR"
longitude = -67.477
latitude = 15.287
type = "wave_buoy"

[[station]]
name = "42060"
ndbc_id = "42060"
longname = "Caribbean Valley - 63 NM WSW of Montserrat"
longitude = -63.331
latitude = 16.433
type = "wave_buoy"

[[station]]
name = "44005"
ndbc_id = "44005"
longname = "GULF OF MAINE - 78 NM East of Portsmouth, NH"
longitude = -69.127
latitude = 43.201
type = "wave_buoy"

[[station]]
name = "44007"
ndbc_id = "44007"
longname = "PORTLAND - 12 NM Southeast of Portland,ME"
longitude = -70.14
latitude = 43.525
type = "wave_buoy"

[[station]]
name = "44008"
ndbc_id = "44008"
longname = "NANTUCKET 54 NM Southeast of Nantucket"
longitude = -69.251
latitude = 40.498
type = "wave_buoy"

[[station]]
name = "44009"
ndbc_id = "44009"
longname = "DELAWARE BAY 26 NM Southeast of Cape May, NJ"
longitude = -74.684
latitude = 38.451
type = "wave_buoy"

[[station]]
name = "44011"
ndbc_id = "44011"
longname = "GEORGES BANK 170 NM East of Hyannis, MA"
longitude = -66.562
latitude = 41.093
type = "wave_buoy"

[[station]]
name = "44013"
ndbc_id = "44013"
longname = "BOSTON 16 NM East of Boston, MA"
longitude = -70.651
latitude = 42.346
type = "wave_buoy"

[[station]]
name = "44014"
ndbc_id = "44014"
longname = "VIRGINIA BEACH 64 NM East of Virginia Beach, VA"
longitude = -74.842
latitude = 36.609
type = "wave_buoy"

[[station]]
name = "44017"
ndbc_id = "44017"
longname = "MONTAUK POINT - 23 NM SSW of Montauk Point, NY"
longitude = -72.049
latitude = 40.693
type = "wave_buoy"

[[station]]
name = "44018"
ndbc_id = "44018"
longname = "CAPE COD - 9 NM North of Provincetown, MA"
longitude = -70.143
latitude = 42.206
type = "wave_buoy"

[[station]]
name = "44020"
ndbc_id = "44020"
longname = "NANTUCKET SOUND"
longitude = -70.279
latitude = 41.493
type = "wave_buoy"

[[station]]
name = "44025"
ndbc_id = "44025"
longname = "LONG ISLAND - 30 NM South of Islip, NY"
longitude = -73.164
latitude = 40.251
type = "wave_buoy"

[[station]]
name = "44027"
ndbc_id = "44027"
longname = "Jonesport, ME - 20 NM SE of Jonesport, ME"
longitude = -67.3
latitude = 44.283
type = "wave_buoy"

[[station]]
name = "44065"
ndbc_id = "44065"
longname = "New York Harbor Entrance - 15 NM SE of Breezy Point , NY"
longitude = -73.703
latitude = 40.369
type = "wave_buoy"

[[station]]
name = "44066"
ndbc_id = "44066"
longname = "Texas Tower #4 - 75 NM East of Long Beach, NJ"
longitude = -72.644
latitude = 39.618
type = "wave_buoy"

[[station]]
name = "45001"
ndbc_id = "45001"
longname = "MID SUPERIOR- 60 NM North Northeast Hancock, MI"
longitude = -87.793
latitude = 48.061
type = "wave_buoy"

[[station]]
name = "45002"
ndbc_id = "45002"
longname = "NORTH MICHIGAN- Halfway between North Manitou and Washington Islands."
longitude = -86.411
latitude = 45.344
type = "wave_buoy"

[[station]]
name = "45003"
ndbc_id = "45003"
longname = "NORTH HURON - 32NM Northeast of Alpena, MI"
longitude = -82.84
latitude = 45.351
type = "wave_buoy"

[[station]]
name = "45004"
ndbc_id = "45004"
longname = "EAST SUPERIOR -70 NM NE Marquette, MI"
longitude = -86.585
latitude = 47.585
type = "wave_buoy"

[[station]]
name = "45005"
ndbc_id = "45005"
longname = "WEST ERIE - 16 NM NW of Lorain, OH"
longitude = -82.398
latitude = 41.677
type = "wave_buoy"

[[station]]
name = "45006"
ndbc_id = "45006"
longname = "WEST SUPERIOR - 30NM NE of Outer Island, WI"
longitude = -89.793
latitude = 47.335
type = "wave_buoy"

[[station]]
name = "45007"
ndbc_id = "45007"
longname = "SOUTH MICHIGAN - 43NM East Southeast of Milwaukee, WI"
longitude = -87.026
latitude = 42.674
type = "wave_buoy"

[[station]]
name = "45008"
ndbc_id = "45008"
longname = "SOUTH HURON - 43NM East of Oscoda, MI"
longitude = -82.416
latitude = 44.283
type = "wave_buoy"

[[station]]
name = "45012"
ndbc_id = "45012"
longname = "EAST Lake Ontario  - 20NM North Northeast of Rochester, NY"
longitude = -77.401
latitude = 43.621
type = "wave_buoy"

[[station]]
name = "46001"
ndbc_id = "46001"
longname = "WESTERN GULF OF ALASKA  - 175NM SE of Kodiak, AK"
longitude = -147.949
latitude = 56.232
type = "wave_buoy"

[[station]]
name = "46002"
ndbc_id = "46002"
longname = "WEST OREGON - 275NM West of Coos Bay, OR"
longitude = -130.502
latitude = 42.658
type = "wave_buoy"

[[station]]
name = "46005"
ndbc_id = "46005"
longname = "WEST WASHINGTON - 300NM West of Aberdeen, WA"
longitude = -131.079
latitude = 46.134
type = "wave_buoy"

[[station]]
name = "46006"
ndbc_id = "46006"
longname = "SOUTHEAST PAPA - 600NM West of Eureka, CA"
longitude = -137.379
latitude = 40.766
type = "wave_buoy"

[[station]]
name = "46011"
ndbc_id = "46011"
longname = "SANTA MARIA - 21NM NW of Point Arguello, CA"
longitude = -121.019
latitude = 34.956
type = "wave_buoy"

[[station]]
name = "46012"
ndbc_id = "46012"
longname = "HALF MOON BAY - 24NM SSW of San Francisco, CA"
longitude = -122.881
latitude = 37.356
type = "wave_buoy"

[[station]]
name = "46013"
ndbc_id = "46013"
longname = "BODEGA BAY - 48NM NW of San Francisco, CA"
longitude = -123.303
latitude = 38.253
type = "wave_buoy"

[[station]]
name = "46014"
ndbc_id = "46014"
longname = "PT ARENA - 19NM North of Point Arena, CA"
longitude = -123.974
latitude = 39.231
type = "wave_buoy"

[[station]]
name = "46015"
ndbc_id = "46015"
longname = "PORT ORFORD - 15 NM West of Port Orford, OR"
longitude = -124.844
latitude = 42.752
type = "wave_buoy"

[[station]]
name = "46022"
ndbc_id = "46022"
longname = "EEL RIVER - 17NM WSW of Eureka, CA"
longitude = -124.527
latitude = 40.748
type = "wave_buoy"

[[station]]
name = "46025"
ndbc_id = "46025"
longname = "Santa Monica Basin - 33NM WSW of Santa Monica, CA"
longitude = -119.044
latitude = 33.758
type = "wave_buoy"

[[station]]
name = "46026"
ndbc_id = "46026"
longname = "SAN FRANCISCO - 18NM West of San Francisco, CA"
longitude = -122.839
latitude = 37.754
type = "wave_buoy"

[[station]]
name = "46027"
ndbc_id = "46027"
longname = "ST GEORGES - 8 NM NW of Crescent City, CA"
longitude = -124.38
latitude = 41.852
type = "wave_buoy"

[[station]]
name = "46028"
ndbc_id = "46028"
longname = "CAPE SAN MARTIN - 55NM West NW of Morro Bay, CA"
longitude = -121.903
latitude = 35.77
type = "wave_buoy"

[[station]]
name = "46029"
ndbc_id = "46029"
longname = "COLUMBIA RIVER BAR - 20NM West of Columbia River Mouth"
longitude = -124.485
latitude = 46.143
type = "wave_buoy"

[[station]]
name = "46035"
ndbc_id = "46035"
longname = "CENTRAL BERING SEA - 310 NM North of Adak, AK"
longitude = -177.703
latitude = 57.016
type = "wave_buoy"

[[station]]
name = "46041"
ndbc_id = "46041"
longname = "CAPE ELIZABETH- 45NM NW of Aberdeen, WA"
longitude = -124.742
latitude = 47.353
type = "wave_buoy"

[[station]]
name = "46042"
ndbc_id = "46042"
longname = "MONTEREY - 27NM WNW of Monterey, CA"
longitude = -122.398
latitude = 36.785
type = "wave_buoy"

[[station]]
name = "46047"
ndbc_id = "46047"
longname = "TANNER BANK - 121 NM West of San Diego, CA"
longitude = -119.525
latitude = 32.388
type = "wave_buoy"

[[station]]
name = "46050"
ndbc_id = "46050"
longname = "STONEWALL BANK - 20NM West of Newport, OR"
longitude = -124.546
latitude = 44.669
type = "wave_buoy"

[[station]]
name = "46053"
ndbc_id = "46053"
longname = "EAST SANTA BARBARA  - 12NM Southwest of Santa Barbara, CA"
longitude = -119.839
latitude = 34.241
type = "wave_buoy"

[[station]]
name = "46054"
ndbc_id = "46054"
longname = "WEST SANTA BARBARA  38 NM West of Santa Barbara, CA"
longitude = -120.47
latitude = 34.273
type = "wave_buoy"

[[station]]
name = "46059"
ndbc_id = "46059"
longname = "WEST CALIFORNIA - 357NM West of San Francisco, CA"
longitude = -129.951
latitude = 38.094
type = "wave_buoy"

[[station]]
name = "46060"
ndbc_id = "46060"
longname = "WEST ORCA BAY - 8NM NW of Hinchinbrook Is., AK"
longitude = -147.9614
latitude = 60.5201
type = "wave_buoy"

[[station]]
name = "46061"
ndbc_id = "46061"
longname = "Seal Rocks - Between Montague and Hinchinbrook Islands, AK"
longitude = -146.833
latitude = 60.238
type = "wave_buoy"

[[station]]
name = "46066"
ndbc_id = "46066"
longname = "SOUTH KODIAK - 310NM SSW of Kodiak, AK"
longitude = -155.009
latitude = 52.765
type = "wave_buoy"

[[station]]
name = "46069"
ndbc_id = "46069"
longname = "SOUTH SANTA ROSA IS. CA"
longitude = -120.213
latitude = 33.677
type = "wave_buoy"

[[station]]
name = "46070"
ndbc_id = "46070"
longname = "SOUTHWEST BERING SEA - 142NM NNE OF ATTU IS, AK"
longitude = 175.183
latitude = 55.008
type = "wave_buoy"

[[station]]
name = "46071"
ndbc_id = "46071"
longname = "WESTERN ALEUTIANS - 14NM SOUTH OF AMCHITKA IS, AK "
longitude = 179.012
latitude = 51.125
type = "wave_buoy"

[[station]]
name = "46072"
ndbc_id = "46072"
longname = "CENTRAL ALEUTIANS 230 NM SW Dutch Harbor"
longitude = -172.088
latitude = 51.672
type = "wave_buoy"

[[station]]
name = "46073"
ndbc_id = "46073"
longname = "SOUTHEAST BERING SEA - 205 NM WNW of Dutch Harbor, AK"
longitude = -172.002
latitude = 55.009
type = "wave_buoy"

[[station]]
name = "46075"
ndbc_id = "46075"
longname = "SHUMAGIN ISLANDS - 85NM South of Sand Point, AK"
longitude = -160.794
latitude = 53.969
type = "wave_buoy"

[[station]]
name = "46076"
ndbc_id = "46076"
longname = "CAPE CLEARE - 17 NM South of Montague Is,  AK"
longitude = -148.009
latitude = 59.471
type = "wave_buoy"

[[station]]
name = "46077"
ndbc_id = "46077"
longname = "SHELIKOF STRAIT, AK"
longitude = -154.176
latitude = 57.902
type = "wave_buoy"

[[station]]
name = "46078"
ndbc_id = "46078"
longname = "ALBATROSS BANK - 104NM South of Kodiak Is., AK"
longitude = -152.582
latitude = 55.556
type = "wave_buoy"

[[station]]
name = "46080"
ndbc_id = "46080"
longname = "PORTLOCK BANK- 76 NM ENE of Kodiak, AK"
longitude = -150.042
latitude = 57.947
type = "wave_buoy"

[[station]]
name = "46081"
ndbc_id = "46081"
longname = "Western Prince William Sound"
longitude = -148.283
latitude = 60.802
type = "wave_buoy"

[[station]]
name = "46082"
ndbc_id = "46082"
longname = "Cape Suckling - 35 NM SE of Kayak Is, AK"
longitude = -143.372
latitude = 59.681
type = "wave_buoy"

[[station]]
name = "46083"
ndbc_id = "46083"
longname = "FAIRWEATHER GROUND - 105 NM West  of Juneau, AK"
longitude = -138.019
latitude = 58.27
type = "wave_buoy"

[[station]]
name = "46084"
ndbc_id = "46084"
longname = "CAPE EDGECUMBE - 25NM SSW of Cape Edgecumbe, AK"
longitude = -136.102
latitude = 56.622
type = "wave_buoy"

[[station]]
name = "46085"
ndbc_id = "46085"
longname = "CENTRAL GULF OF ALASKA -  265NM West of Cape Ommaney, AK"
longitude = -142.882
latitude = 55.883
type = "wave_buoy"

[[station]]
name = "46086"
ndbc_id = "46086"
longname = "SAN CLEMENTE BASIN - 27NM SE Of San Clemente Is, CA"
longitude = -118.052
latitude = 32.499
type = "wave_buoy"

[[station]]
name = "46087"
ndbc_id = "46087"
longname = "Neah Bay - 6 NM North of Cape Flattery, WA     (Traffic Separation Lighted Buoy)"
longitude = -124.726
latitude = 48.493
type = "wave_buoy"

[[station]]
name = "46088"
ndbc_id = "46088"
longname = "NEW DUNGENESS - 17 NM NE of Port Angeles, WA"
longitude = -123.179
latitude = 48.332
type = "wave_buoy"

[[station]]
name = "46089"
ndbc_id = "46089"
longname = "TILLAMOOK, OR - 85 NM WNW of Tillamook, OR"
longitude = -125.785
latitude = 45.933
type = "wave_buoy"

[[station]]
name = "51000"
ndbc_id = "51000"
longname = "NORTHERN HAWAII ONE - 245NM NE of Honolulu HI"
longitude = -153.792
latitude = 23.528
type = "wave_buoy"

[[station]]
name = "51001"
ndbc_id = "51001"
longname = "NORTHWESTERN HAWAII ONE - 188 NM NW of Kauai Island, HI"
longitude = -162.0
latitude = 24.453
type = "wave_buoy"

[[station]]
name = "51002"
ndbc_id = "51002"
longname = "SOUTHWEST HAWAII - 215NM SSW of Hilo, HI"
longitude = -157.742
latitude = 17.043
type = "wave_buoy"

[[station]]
name = "51003"
ndbc_id = "51003"
longname = "WESTERN  HAWAII - 205 NM SW of Honolulu, HI"
longitude = -160.639
latitude = 19.196
type = "wave_buoy"

[[station]]
name = "51004"
ndbc_id = "51004"
longname = "SOUTHEAST HAWAII - 205 NM Southeast of Hilo, HI"
longitude = -152.255
latitude = 17.533
type = "wave_buoy"

[[station]]
name = "51101"
ndbc_id = "51101"
longname = "NORTHWESTERN HAWAII TWO - 186 NM NW of Kauai Is., HI   "
longitude = -162.075
latitude = 24.361
type = "wave_buoy"

