[[station]]
name = "41043"
ndbc_id = "41043"
longname = "NE PUERTO RICO - 170 NM NNE of San Juan, PR"
longitude = -64.79
latitude = 21.03
type = "wave_buoy"

[[station]]
name = "41044"
ndbc_id = "41044"
longname = "NE ST MARTIN - 330 NM NE St Martin Is"
longitude = -58.63
latitude = 21.582
type = "wave_buoy"

[[station]]
name = "41046"
ndbc_id = "41046"
longname = "EAST BAHAMAS - 335 NM East of San Salvador Is,  Bahamas "
longitude = -68.384
latitude = 23.822
type = "wave_buoy"

[[station]]
name = "41047"
ndbc_id = "41047"
longname = "NE BAHAMAS - 350 NM ENE of Nassau, Bahamas"
longitude = -71.466
latitude = 27.463
type = "wave_buoy"

[[station]]
name = "41049"
ndbc_id = "41049"
longname = "SOUTH BERMUDA - 300 NM SSE of Bermuda"
longitude = -62.938
latitude = 27.49
type = "wave_buoy"

[[station]]
name = "41052"
ndbc_id = "41052"
longname = "South of St. John, VI"
longitude = -64.763
latitude = 18.249
type = "wave_buoy"

[[station]]
name = "42059"
ndbc_id = "42059"
longname = "Eastern Caribbean Sea - 180 NM SSW of Ponce, PR"
longitude = -67.477
latitude = 15.287
type = "wave_buoy"

[[station]]
name = "42060"
ndbc_id = "42060"
longname = "Caribbean Valley - 63 NM WSW of Montserrat"
longitude = -63.331
latitude = 16.433
type = "wave_buoy"

[[station]]
name = "42085"
ndbc_id = "42085"
longname = "Southeast of Ponce, PR"
longitude = -66.537
latitude = 17.87
type = "wave_buoy"

