[[station]]
name = "8775870"
coops_id = "8775870"
longname = "Bob Hall Pier, Corpus Christi, TX"
longitude = -97.2167
latitude = 27.58
type = "tide_gauge"
mllw = -0.284
water_level_correction = 0.0

[[station]]
name = "8771341"
coops_id = "8771341"
longname = "Galveston Bay Entrance, North Jetty, TX"
longitude = -94.725
latitude = 29.3567
type = "tide_gauge"
mllw = -0.297
water_level_correction = 0.0

[[station]]
name = "8760922"
coops_id = "8760922"
longname = "Pilots Station East, S.W. Pass, LA"
longitude = -89.4067
latitude = 28.9317
type = "tide_gauge"
mllw = -0.178
water_level_correction = 0.0

[[station]]
name = "8729210"
coops_id = "8729210"
longname = "Panama City Beach, FL"
longitude = -85.8783
latitude = 30.2133
type = "tide_gauge"
mllw = -0.203
water_level_correction = 0.0

[[station]]
name = "8727520"
coops_id = "8727520"
longname = "Cedar Key, FL"
longitude = -83.0317
latitude = 29.135
longitude_model = -83.0917
latitude_model = 29.135
type = "tide_gauge"
mllw = -0.621
water_level_correction = 0.0

[[station]]
name = "8725110"
coops_id = "8725110"
longname = "Naples, FL"
longitude = -81.8083
latitude = 26.1317
type = "tide_gauge"
mllw = -0.502
water_level_correction = 0.0

[[station]]
name = "8443970"
coops_id = "8443970"
longname = "Boston, MA"
longitude = -71.0533
latitude = 42.355
longitude_model = -70.981736
latitude_model = 42.336355
type = "tide_gauge"
mllw = -1.586
water_level_correction = 0.15

[[station]]
name = "8510560"
coops_id = "8510560"
longname = "Montauk, NY"
longitude = -71.96
latitude = 41.06
longitude_model = -71.987089
latitude_model = 41.069476
type = "tide_gauge"
mllw = -0.377
water_level_correction = 0.15

[[station]]
name = "8531680"
coops_id = "8531680"
longname = "Sandy Hook, NJ"
longitude = -74.01
latitude = 40.4667
type = "tide_gauge"
mllw = -0.785
water_level_correction = 0.15

[[station]]
name = "8534720"
coops_id = "8534720"
longname = "Atlantic City, NJ"
longitude = -74.4183
latitude = 39.3567
type = "tide_gauge"
mllw = -0.675
water_level_correction = 0.15

[[station]]
name = "8570283"
coops_id = "8570283"
longname = "Ocean City Inlet, MD"
longitude = -75.0917
latitude = 38.3283
longitude_model = -75.0717
latitude_model = 38.3283
type = "tide_gauge"
mllw = -0.387
water_level_correction = 0.15

[[station]]
name = "8638901"
coops_id = "8638901"
longname = "CBBT, Chesapeake Channel, VA"
longitude = -76.0833
latitude = 37.0333
type = "tide_gauge"
mllw = -0.441
water_level_correction = 0.15

[[station]]
name = "8651370"
coops_id = "8651370"
longname = "Duck, NC"
longitude = -75.7467
latitude = 36.1833
type = "tide_gauge"
mllw = -0.539
water_level_correction = 0.15

[[station]]
name = "8658163"
coops_id = "8658163"
longname = "Wrightsville Beach, NC"
longitude = -77.7867
latitude = 34.2133
type = "tide_gauge"
mllw = -0.658
water_level_correction = 0.15

[[station]]
name = "8661070"
coops_id = "8661070"
longname = "Springmaid Pier, SC"
longitude = -78.9183
latitude = 33.655
type = "tide_gauge"
mllw = -0.826
water_level_correction = 0.15

[[station]]
name = "8670870"
coops_id = "8670870"
longname = "Fort Pulaski, GA"
longitude = -80.9017
latitude = 32.0367
longitude_model = -80.8017
latitude_model = 32.0367
type = "tide_gauge"
mllw = -1.164
water_level_correction = 0.15

[[station]]
name = "8720218"
coops_id = "8720218"
longname = "Mayport Bar Pilots Dock, FL"
longitude = -81.4283
latitude = 30.3983
longitude_model = -81.37
latitude_model = 30.3983
type = "tide_gauge"
mllw = -0.752
water_level_correction = 0.15

[[station]]
name = "8721604"
coops_id = "8721604"
longname = "Trident Pier, Port Canaveral, FL"
longitude = -80.5933
latitude = 28.415
longitude_model = -80.55
latitude_model = 28.415
type = "tide_gauge"
mllw = -0.572
water_level_correction = 0.15

