[[station]]
name = "FLWAK03364"
id = "FLWAK03364"
longname = "St. Marks River Public Boat Ramp"
longitude = -84.20905
latitude = 30.151825
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLFRA26263"
id = "FLFRA26263"
longname = "Alligator Point on the beach to the west of Beach Academy, just to the east of the intersection of Harbor Circle and Alligator Drive"
longitude = -84.37364
latitude = 29.89392
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLWAL26240"
id = "FLWAL26240"
longname = "Seagrove Beach"
longitude = -86.1423028
latitude = 30.3204393
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLOKA03301"
id = "FLOKA03301"
longname = "Choctwahatchee Bay at Meigs Neighborhood Park"
longitude = -86.58439
latitude = 30.44343
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLGUL03263"
id = "FLGUL03263"
longname = "Indian Pass Campground Boat Ramp"
longitude = -85.2220594
latitude = 29.6831221
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLWAL26241"
id = "FLWAL26241"
longname = "Santa Clara Beach Public Access #17"
longitude = -86.1192
latitude = 30.3138
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLLEV25006"
id = "FLLEV25006"
longname = "Wacasassa Park Boat Ramp"
longitude = -82.76366
latitude = 29.21371
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLDIX03354"
id = "FLDIX03354"
longname = "Jena Boat Ramp"
longitude = -83.389081
latitude = 29.670051
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLTAY03358"
id = "FLTAY03358"
longname = "Deckle Beach Blvd"
longitude = -83.61783
latitude = 29.84755
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLGUL26254"
id = "FLGUL26254"
longname = "William J. Rish Recreational Park on piling of ramp to beach"
longitude = -85.391434
latitude = 29.726783
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLFRA26257"
id = "FLFRA26257"
longname = "Saint George Island State Park"
longitude = -84.76186
latitude = 29.70314
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLDIX03353"
id = "FLDIX03353"
longname = "Rocky Creek Boat Ramp"
longitude = -83.390162
latitude = 29.596659
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLGUL03280"
id = "FLGUL03280"
longname = "Pier #3 of St Joseph Peninsula State Park"
longitude = -85.404958
latitude = 29.766313
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLLEV03349"
id = "FLLEV03349"
longname = "Cedar Key"
longitude = -83.03002
latitude = 29.13589
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLTAY03359"
id = "FLTAY03359"
longname = "Spring Warrior Fish Camp"
longitude = -83.67024
latitude = 29.93017
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLFRA03276"
id = "FLFRA03276"
longname = "Apalachicola Bay at Battery Park"
longitude = -84.98297
latitude = 29.723175
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLTAY03356"
id = "FLTAY03356"
longname = "Keaton Beach"
longitude = -83.59493
latitude = 29.81891
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLLEV24997"
id = "FLLEV24997"
longname = "Shell Mound Boat Ramp and Observation Deck"
longitude = -83.068865
latitude = 29.206914
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLDIX03352"
id = "FLDIX03352"
longname = "Butler Douglas Memorial Park Boat Ramp"
longitude = -83.292865
latitude = 29.439765
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLWAL26383"
id = "FLWAL26383"
longname = "Miramar Public Beach"
longitude = -86.3874594
latitude = 30.3779979
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLTAY25003"
id = "FLTAY25003"
longname = "Dark Island Public Boat Ramp"
longitude = -83.58876
latitude = 29.80401
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLBAY26247"
id = "FLBAY26247"
longname = "St Andrews State Park"
longitude = -85.74319
latitude = 30.13164
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLTAY03355"
id = "FLTAY03355"
longname = "Hagens Cove Park"
longitude = -83.579528
latitude = 29.773025
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLWAK03369"
id = "FLWAK03369"
longname = "Ochlockonee Bay"
longitude = -84.383625
latitude = 29.977355
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLLEV25005"
id = "FLLEV25005"
longname = "McCormick Creek Boat Ramp"
longitude = -83.062464
latitude = 29.291031
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLDIX03351"
id = "FLDIX03351"
longname = "Shired Island"
longitude = -83.20546294
latitude = 29.39871309
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLBAY03283"
id = "FLBAY03283"
longname = "Mexico Beach Pier"
longitude = -85.424604
latitude = 29.948982
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLWAL03347"
id = "FLWAL03347"
longname = "Santa Rosa Beach"
longitude = -86.2485
latitude = 30.3518
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLTAY24950"
id = "FLTAY24950"
longname = "Big Bend Wildlife Management Area Boat Ramp"
longitude = -83.48648
latitude = 29.72152
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLTAY03360"
id = "FLTAY03360"
longname = "Hampton Springs Boat Ramp"
longitude = -83.775877
latitude = 29.995918
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLDIX03350"
id = "FLDIX03350"
longname = "Demory Creek Boat Ramp"
longitude = -83.143337
latitude = 29.330347
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLDIX24951"
id = "FLDIX24951"
longname = "Highway 361 Boat Ramp"
longitude = -83.373951
latitude = 29.524242
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLTAY17325"
id = "FLTAY17325"
longname = "Aucilla River Boat Ramp"
longitude = -83.979546
latitude = 30.11648
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

[[station]]
name = "FLTAY03362"
id = "FLTAY03362"
longname = "Ecofina River State Park Boat Ramp"
longitude = -83.90017
latitude = 30.066463
type = "tide_gauge"
source = "usgs_fev"
vertical_datum = "NAVD88"

