[conda]
path = "c:\\work\\miniconda3"
env = "cosmos"

[model_database]
path = "c:\\work\\cosmos\\model_database"

[meteo_database]
path = "c:\\work\\cosmos\\meteo_database"

[executables]
delft3dfm_path = "yourdelft3dfmpath"
sfincs_path    = "c:\\work\\checkouts\\git\\SFINCS\\source\\sfincs\\x64\\Release"
hurrywave_path = "c:\\work\\checkouts\\git\\HurryWave\\source\\hurrywave\\x64\\Release"
beware_path    = "c:\\work\\cosmos\\exe\\beware"
xbeach_path    = "yourxbeachpath"

[webserver]
hostname = ""
path     = ""
username = ""
password = ""

[webviewer]
name    = "my_viewer"
version = "version02"
lon     = -85.0
lat     = 25.0
zoom    = 6

[track_ensemble]
nr_realizations = 3
mean_abs_cte24 = 19.0397
sc_cte = 1.3253
mean_abs_ate24 = 26.224
sc_ate = 1.3432
mean_abs_ve24 = 6.9858
sc_ve = 1.0000
bias_ve = 0.0

[cloud_config]
host            = ""
access_key      = ""
secret_key      = ""
region          = ""
token           = ""

[run]
mode                  = "single_shot"
interval              = 6
clean_up              = false
make_flood_maps       = true
make_wave_maps        = true
make_sedero_maps      = true
make_water_level_maps = true
make_meteo_maps       = false
upload                = false
download_meteo        = true
run_mode              = "serial"
event_mode            = "meteo"
only_run_ensemble     = false
remove_old_cycles     = 24
dthis                 = 600.0
dtmap                 = 3600.0
dtmax                 = 21600.0
