[[meteo_dataset]]
name = "coamps_tc_forecast_north_atlantic"
source = "coamps_tc_forecast"
x_range = [ -100.0, -1.0,]
y_range = [ -8.0, 80.0,]

[[meteo_dataset]]
name = "ECMWF_philippines_windu_windv_pressure"
source = "gfs_analysis_0p50"
x_range = [ 100.0, 266.0,]
y_range = [ -43.0, 43.0,]

[[meteo_dataset]]
name = "spiderwebs"
source = "jtwc"

[[meteo_dataset]]
name = "tracks"
source = "jtwc"

