[[meteo_subset]]
name = "coamps_tc_forecast_north_atlantic"
source = "coamps_tc_forecast"
x_range = [ -100.0, -1.0,]
y_range = [ -8.0, 80.0,]

[[meteo_subset]]
name = "spiderwebs"
source = "jtwc"

[[meteo_subset]]
name = "tracks"
source = "jtwc"

